"""Repository protocols (ports) — concrete implementations live in
`memory.py` (default for dev/test) and `supabase_repo.py` (production)."""
from __future__ import annotations

from typing import Protocol

from app.domain.entities import (
    Organization,
    Platform,
    Post,
    ReviewSession,
    Source,
    Trigger,
    User,
    Workflow,
    WorkflowRun,
)
from app.domain.value_objects.ids import (
    OrgId,
    PlatformId,
    PostId,
    ReviewId,
    RunId,
    SourceId,
    TriggerId,
    UserId,
    WorkflowId,
)


class UserRepository(Protocol):
    async def get(self, user_id: UserId) -> User | None: ...
    async def get_by_subject(self, subject: str) -> User | None: ...
    async def upsert(self, user: User) -> User: ...


class OrganizationRepository(Protocol):
    async def get(self, org_id: OrgId) -> Organization | None: ...
    async def upsert(self, org: Organization) -> Organization: ...


class PlatformRepository(Protocol):
    async def add(self, platform: Platform) -> Platform: ...
    async def get(self, org_id: OrgId, platform_id: PlatformId) -> Platform | None: ...
    async def list(self, org_id: OrgId) -> list[Platform]: ...
    async def update(self, platform: Platform) -> Platform: ...


class SourceRepository(Protocol):
    async def add(self, source: Source) -> Source: ...
    async def get(self, org_id: OrgId, source_id: SourceId) -> Source | None: ...
    async def list(self, org_id: OrgId) -> list[Source]: ...
    async def update(self, source: Source) -> Source: ...


class WorkflowRepository(Protocol):
    async def add(self, workflow: Workflow) -> Workflow: ...
    async def get(self, org_id: OrgId, workflow_id: WorkflowId) -> Workflow | None: ...
    async def list(self, org_id: OrgId) -> list[Workflow]: ...
    async def update(self, workflow: Workflow) -> Workflow: ...


class WorkflowRunRepository(Protocol):
    async def add(self, run: WorkflowRun) -> WorkflowRun: ...
    async def get(self, org_id: OrgId, run_id: RunId) -> WorkflowRun | None: ...
    async def list_for_workflow(self, org_id: OrgId, workflow_id: WorkflowId) -> list[WorkflowRun]: ...
    async def update(self, run: WorkflowRun) -> WorkflowRun: ...


class PostRepository(Protocol):
    async def add(self, post: Post) -> Post: ...
    async def get(self, org_id: OrgId, post_id: PostId) -> Post | None: ...
    async def list(self, org_id: OrgId, *, status: str | None = None) -> list[Post]: ...
    async def update(self, post: Post) -> Post: ...


class TriggerRepository(Protocol):
    async def add(self, trigger: Trigger) -> Trigger: ...
    async def get(self, org_id: OrgId, trigger_id: TriggerId) -> Trigger | None: ...
    async def get_any(self, trigger_id: TriggerId) -> Trigger | None: ...
    async def list(self, org_id: OrgId, *, plugin_name: str | None = None) -> list[Trigger]: ...
    async def update(self, trigger: Trigger) -> Trigger: ...


class ReviewSessionRepository(Protocol):
    async def add(self, review: ReviewSession) -> ReviewSession: ...
    async def get(self, org_id: OrgId, review_id: ReviewId) -> ReviewSession | None: ...
    async def get_by_message_ref(self, channel: str, ref: str) -> ReviewSession | None: ...
    async def latest_pending_for(self, channel: str, sender: str) -> ReviewSession | None: ...
    async def list_open(self, org_id: OrgId) -> list[ReviewSession]: ...
    async def update(self, review: ReviewSession) -> ReviewSession: ...
