"""Repository protocols (ports) — concrete implementations live in
`memory.py` (default for dev/test) and `supabase_repo.py` (production)."""
from __future__ import annotations

from typing import Protocol

from app.domain.entities import (
    ApprovalPolicy,
    ApprovalRequest,
    Campaign,
    DataExportJob,
    Experiment,
    Organization,
    Platform,
    Post,
    RecyclePolicy,
    ReviewSession,
    Source,
    Trigger,
    User,
    Workflow,
    WorkflowRun,
)
from app.domain.value_objects.ids import (
    ApprovalPolicyId,
    ApprovalRequestId,
    CampaignId,
    DataExportJobId,
    ExperimentId,
    OrgId,
    PlatformId,
    PostId,
    RecyclePolicyId,
    ReviewId,
    RunId,
    SourceId,
    TriggerId,
    UserId,
    WorkflowId,
)


class UserRepository(Protocol):
    async def get(self, user_id: UserId) -> User | None: ...
    async def get_by_subject(self, subject: str) -> User | None: ...
    async def upsert(self, user: User) -> User: ...


class OrganizationRepository(Protocol):
    async def get(self, org_id: OrgId) -> Organization | None: ...
    async def upsert(self, org: Organization) -> Organization: ...


class PlatformRepository(Protocol):
    async def add(self, platform: Platform) -> Platform: ...
    async def get(self, org_id: OrgId, platform_id: PlatformId) -> Platform | None: ...
    async def list(self, org_id: OrgId) -> list[Platform]: ...
    async def update(self, platform: Platform) -> Platform: ...
    async def delete(self, org_id: OrgId, platform_id: PlatformId) -> None: ...


class SourceRepository(Protocol):
    async def add(self, source: Source) -> Source: ...
    async def get(self, org_id: OrgId, source_id: SourceId) -> Source | None: ...
    async def list(self, org_id: OrgId) -> list[Source]: ...
    async def update(self, source: Source) -> Source: ...
    async def delete(self, org_id: OrgId, source_id: SourceId) -> None: ...


class WorkflowRepository(Protocol):
    async def add(self, workflow: Workflow) -> Workflow: ...
    async def get(self, org_id: OrgId, workflow_id: WorkflowId) -> Workflow | None: ...
    async def list(self, org_id: OrgId) -> list[Workflow]: ...
    async def update(self, workflow: Workflow) -> Workflow: ...
    async def delete(self, org_id: OrgId, workflow_id: WorkflowId) -> None: ...
    async def list_active_all_orgs(self) -> list[tuple[OrgId, Workflow]]:
        """Cross-tenant scan used by the Celery Beat scheduler. Returns every
        ``(org_id, workflow)`` pair where the workflow is in the ACTIVE
        state, sorted by org_id for stable iteration. Concrete implementations
        should index on ``status`` so this stays cheap as the org count grows."""
        ...


class WorkflowRunRepository(Protocol):
    async def add(self, run: WorkflowRun) -> WorkflowRun: ...
    async def get(self, org_id: OrgId, run_id: RunId) -> WorkflowRun | None: ...
    async def list_for_workflow(self, org_id: OrgId, workflow_id: WorkflowId) -> list[WorkflowRun]: ...
    async def update(self, run: WorkflowRun) -> WorkflowRun: ...


class PostRepository(Protocol):
    async def add(self, post: Post) -> Post: ...
    async def get(self, org_id: OrgId, post_id: PostId) -> Post | None: ...
    async def list(self, org_id: OrgId, *, status: str | None = None) -> list[Post]: ...
    async def update(self, post: Post) -> Post: ...
    async def delete(self, org_id: OrgId, post_id: PostId) -> None: ...


class TriggerRepository(Protocol):
    async def add(self, trigger: Trigger) -> Trigger: ...
    async def get(self, org_id: OrgId, trigger_id: TriggerId) -> Trigger | None: ...
    async def get_any(self, trigger_id: TriggerId) -> Trigger | None: ...
    async def list(self, org_id: OrgId, *, plugin_name: str | None = None) -> list[Trigger]: ...
    async def update(self, trigger: Trigger) -> Trigger: ...


class ReviewSessionRepository(Protocol):
    async def add(self, review: ReviewSession) -> ReviewSession: ...
    async def get(self, org_id: OrgId, review_id: ReviewId) -> ReviewSession | None: ...
    async def get_by_message_ref(self, channel: str, ref: str) -> ReviewSession | None: ...
    async def latest_pending_for(self, channel: str, sender: str) -> ReviewSession | None: ...
    async def list_open(self, org_id: OrgId) -> list[ReviewSession]: ...
    async def update(self, review: ReviewSession) -> ReviewSession: ...


class CampaignRepository(Protocol):
    async def add(self, campaign: Campaign) -> Campaign: ...
    async def get(self, org_id: OrgId, campaign_id: CampaignId) -> Campaign | None: ...
    async def list(self, org_id: OrgId, *, status: str | None = None) -> list[Campaign]: ...
    async def list_due(self, now) -> list[Campaign]: ...
    async def update(self, campaign: Campaign) -> Campaign: ...
    async def delete(self, org_id: OrgId, campaign_id: CampaignId) -> None: ...


class ExperimentRepository(Protocol):
    async def add(self, experiment: Experiment) -> Experiment: ...
    async def get(self, org_id: OrgId, experiment_id: ExperimentId) -> Experiment | None: ...
    async def list(
        self, org_id: OrgId, *, status: str | None = None,
    ) -> list[Experiment]: ...
    async def list_running(self) -> list[Experiment]: ...
    async def update(self, experiment: Experiment) -> Experiment: ...
    async def delete(self, org_id: OrgId, experiment_id: ExperimentId) -> None: ...


class ApprovalPolicyRepository(Protocol):
    async def add(self, policy: ApprovalPolicy) -> ApprovalPolicy: ...
    async def get(self, org_id: OrgId, policy_id: ApprovalPolicyId) -> ApprovalPolicy | None: ...
    async def list(self, org_id: OrgId) -> list[ApprovalPolicy]: ...
    async def update(self, policy: ApprovalPolicy) -> ApprovalPolicy: ...
    async def delete(self, org_id: OrgId, policy_id: ApprovalPolicyId) -> None: ...


class ApprovalRequestRepository(Protocol):
    async def add(self, request: ApprovalRequest) -> ApprovalRequest: ...
    async def get(
        self, org_id: OrgId, request_id: ApprovalRequestId,
    ) -> ApprovalRequest | None: ...
    async def list_open(self, org_id: OrgId) -> list[ApprovalRequest]: ...
    async def list_for_post(
        self, org_id: OrgId, post_id: PostId,
    ) -> list[ApprovalRequest]: ...
    async def update(self, request: ApprovalRequest) -> ApprovalRequest: ...


class RecyclePolicyRepository(Protocol):
    async def add(self, policy: RecyclePolicy) -> RecyclePolicy: ...
    async def get(self, org_id: OrgId, policy_id: RecyclePolicyId) -> RecyclePolicy | None: ...
    async def list(self, org_id: OrgId) -> list[RecyclePolicy]: ...
    async def list_due(self, now) -> list[RecyclePolicy]: ...
    async def update(self, policy: RecyclePolicy) -> RecyclePolicy: ...
    async def delete(self, org_id: OrgId, policy_id: RecyclePolicyId) -> None: ...


class DataExportJobRepository(Protocol):
    async def add(self, job: DataExportJob) -> DataExportJob: ...
    async def get(self, org_id: OrgId, job_id: DataExportJobId) -> DataExportJob | None: ...
    async def list(self, org_id: OrgId) -> list[DataExportJob]: ...
    async def list_pending(self) -> list[DataExportJob]: ...
    async def update(self, job: DataExportJob) -> DataExportJob: ...
