/**
 * Auto-generated by Supabase MCP from project `SocialMediaManagement`.
 * Regenerate with: `supabase gen types typescript --project-id ukaulrxhegrqyfrirnkb`
 *
 * NOTE: Supabase's type generator only emits the `public` schema. Our domain
 * lives in `smms`. To get full typed access to those tables, either:
 *   1. Expose `smms` to PostgREST in Supabase Dashboard → Project Settings →
 *      API → Exposed Schemas, then regenerate.
 *   2. Or stick with the hand-written types in `lib/api/types.ts` (current
 *      approach — they mirror the FastAPI response shapes).
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: '14.5' };
  public: {
    Tables: { [_ in never]: never };
    Views:  { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums:  { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
