'use client';
import { Card, CardTitle, CardDescription } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { Sidebar } from '@/components/layout/Sidebar';
import { TopBar } from '@/components/layout/TopBar';
import { useApi } from '@/lib/api/client';
import type { Post, Workflow } from '@/lib/api/types';
import { CheckCircle2, AlertTriangle, Send, Bot } from 'lucide-react';

export default function DashboardPage() {
  const { data: workflows } = useApi<Workflow[]>('/workflows');
  const { data: posts } = useApi<Post[]>('/posts');

  const stats = computeStats(posts ?? []);

  return (
    <div className="flex h-screen">
      <Sidebar />
      <div className="flex-1 flex flex-col overflow-hidden">
        <TopBar title="Dashboard" />
        <main className="flex-1 overflow-y-auto p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            <Stat icon={<Send size={16} />} label="Published this week" value={stats.publishedThisWeek} />
            <Stat icon={<Bot size={16} />} label="Active workflows" value={(workflows ?? []).filter(w => w.status === 'active').length} />
            <Stat icon={<CheckCircle2 size={16} />} label="Approval rate" value={`${stats.approvalRate}%`} />
            <Stat icon={<AlertTriangle size={16} />} label="Needs review" value={stats.needsReview} />
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
            <Card className="lg:col-span-2">
              <CardTitle>Recent posts</CardTitle>
              <CardDescription>Generated by your agents</CardDescription>
              <div className="mt-4 divide-y divide-ink-200">
                {(posts ?? []).slice(0, 6).map(p => (
                  <div key={p.id} className="py-3 flex items-start gap-4">
                    <Badge tone={statusTone(p.status)}>{p.status}</Badge>
                    <div className="min-w-0 flex-1">
                      <div className="text-sm text-ink-900 line-clamp-2">{p.text}</div>
                      <div className="text-xs text-ink-500 mt-1">
                        {p.hashtags.join(' ') || 'no hashtags'}
                      </div>
                    </div>
                  </div>
                ))}
                {posts && posts.length === 0 && (
                  <p className="text-sm text-ink-500 py-6">No posts yet — create a workflow to get started.</p>
                )}
              </div>
            </Card>

            <Card>
              <CardTitle>Workflows</CardTitle>
              <CardDescription>Active pipelines</CardDescription>
              <div className="mt-4 space-y-3">
                {(workflows ?? []).slice(0, 6).map(w => (
                  <div key={w.id} className="flex items-center justify-between">
                    <div className="min-w-0">
                      <div className="text-sm font-medium truncate">{w.name}</div>
                      <div className="text-xs text-ink-500">{w.schedule.kind}</div>
                    </div>
                    <Badge tone={w.status === 'active' ? 'success' : 'default'}>{w.status}</Badge>
                  </div>
                ))}
                {workflows && workflows.length === 0 && (
                  <p className="text-sm text-ink-500">No workflows yet.</p>
                )}
              </div>
            </Card>
          </div>
        </main>
      </div>
    </div>
  );
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number | string }) {
  return (
    <Card className="py-4">
      <div className="flex items-center gap-2 text-ink-500 text-xs">{icon}{label}</div>
      <div className="mt-2 text-2xl font-semibold tracking-tight">{value}</div>
    </Card>
  );
}

function statusTone(s: Post['status']) {
  switch (s) {
    case 'published': return 'success';
    case 'failed':    return 'danger';
    case 'review':    return 'warning';
    case 'approved':  return 'info';
    default:          return 'default';
  }
}

function computeStats(posts: Post[]) {
  const now = Date.now();
  const week = 7 * 24 * 60 * 60 * 1000;
  const publishedThisWeek = posts.filter(p =>
    p.published_at && now - new Date(p.published_at).getTime() < week
  ).length;
  const approvalRate = posts.length
    ? Math.round((posts.filter(p => ['approved', 'published'].includes(p.status)).length / posts.length) * 100)
    : 0;
  const needsReview = posts.filter(p => p.status === 'review').length;
  return { publishedThisWeek, approvalRate, needsReview };
}
